### ISSUE TITLE
Missing a function return statement causes an llvm error

### ISSUE THREAD

**Issue by sarmadka** [Alusus/Alusus#1]
Defining a function with a return type and missing the return statement is causing an LLVM assertion error instead of a proper build message.

**Comment by xlmnxp** [comment]
Error message:
```alusus: /media/veracrypt1/Sarmad/Workshop/Alusus/Builds/Dependencies/llvm-3.3.src/include/llvm/Support/Casting.h:97: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = llvm::ReturnInst; From = llvm::TerminatorInst]: Assertion `Val && "isa<> used on a null pointer"' failed.
Stack dump:
0.      Running pass 'CodeGen Prepare' on function '@"ANet.curl_easy_setopt(ptr[ANet.CURL],Int[32],Int[64])=>(Int[32])"'
[1]    6039 abort (core dumped)  alusus tests/test.alusus```

**Comment by xlmnxp** [comment]
fixed 6797050d4a917af7d29020488d5f089a37bf15b8
