### ISSUE TITLE
Documentations: typo in the print function

### ISSUE THREAD

**Issue by ali-sameh-galal** [Alusus/Alusus#199]
``print`` function is written as C ``printf``
https://alusus.org/Documents/Tutorial.ar/1_مقدمة_إلى_لغة_الأسس.html#SetupEnvironment
not a big issue but it will confuse the reader if he try to write it as ``printf`` or assuming that Alusus has a printf function that is different from the print one, like the following:
``` python
import "Srl/Console";
use Srl.Console;
printf("Hello World!\n");
```
he will get ``Unknown symbol`` error:
```sh
$ alusus main.alusus
ERROR SPPA1007 @ /home/aligalal/Alusus/src/main.alusus (3,1): Unknown symbol.
```
![Screenshot from 2022-11-11 17-11-51](https://user-images.githubusercontent.com/66528793/201368911-ebec9a35-db6b-447e-a079-c86cf4dd3014.png)

**Comment by ali-sameh-galal** [comment]
here is another one, it should be ``"منطقية"``

![Screenshot from 2022-11-11 18-28-57](https://user-images.githubusercontent.com/66528793/201386076-7ba04868-29fa-4bca-b4a4-ba6a59bd9543.png)

**Comment by sarmadka** [comment]
Thanks for reporting this. Fixed.
